services:
  frontend:
    build:
      context: .
      dockerfile: ./infrastructure/docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://backend:8080/api/v1
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./infrastructure/docker/backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      PYTHON_API_URL: http://python-api:8081
      EXTERNAL_DATA_MOUNT: /data/shared
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
      GIN_MODE: release
      CONFIG_PATH: /app/config.json
      DB_HOST: postgres-db
      DB_USER: admin
      DB_PASSWORD: adminpass
      DB_NAME: mydatabase
      DB_SSL_MODE: disable
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
    volumes:
      - shared_data:/data/shared
    depends_on:
      - python-api
      - postgres-db
      - redis-db

  python-api:
    build:
      context: ./python_api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - shared_data:/data/shared
    environment:
      PYTHONUNBUFFERED: 1

  postgres-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-db:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  shared_data: {}
  postgres_data: {}
  redis_data: {}
