apiVersion: v1
kind: Secret
metadata:
  name: nivai-fileshare-secrets
  namespace: nivai
type: Opaque
stringData:
  # These placeholder values will be replaced with actual secrets during deployment
  account-name: "${AZURE_STORAGE_ACCOUNT_NAME}"
  account-key: "${AZURE_STORAGE_ACCOUNT_KEY}"
  fileshare-name: "${AZURE_FILESHARE_NAME}"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nivai-fileshare-pv
  labels:
    usage: nivai-data-storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azure-file
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: nivai-fileshare-volume
    volumeAttributes:
      resourceGroup: "${AZURE_RESOURCE_GROUP}"
      storageAccount: "${AZURE_STORAGE_ACCOUNT_NAME}"
      shareName: "${AZURE_FILESHARE_NAME}"
    nodeStageSecretRef:
      name: nivai-fileshare-secrets
      namespace: nivai

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nivai-fileshare-pvc
  namespace: nivai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nivai-fileshare-pv
  storageClassName: azure-file
